name: qodana-backend

on:
  push:
    paths:
      - 'apps/backend/**'
      - 'qodana.yaml'
      - '.github/workflows/qodana-code-quality.yml'
  pull_request:
    paths:
      - 'apps/backend/**'
      - 'qodana.yaml'
      - '.github/workflows/qodana-code-quality.yml'

permissions:
  contents: read
  security-events: write
  pull-requests: write
  checks: write

jobs:
  qodana:
    #disable qodana for now
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with: { fetch-depth: 0 }

      - name: Qodana Scan (Community)
        id: qodana
        uses: JetBrains/qodana-action@v2025.3
        env:
          QODANA_IMAGE: jetbrains/qodana-jvm-community:2025.2
        with:
          use-caches: true
          use-annotations: true
          post-pr-comment: true
          pr-mode: ${{ github.event_name == 'pull_request' }}
          upload-result: true

      - name: Upload SARIF to Code Scanning
        if: ${{ steps.qodana.outcome == 'success' }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json